#!/bin/sh
# Rewrite author with git filter-branch

git filter-branch --env-filter '
OLD_EMAIL="gsotirov"
CORRECT_NAME="Georgi D. Sotirov"
CORRECT_EMAIL="gdsotirov@dir.bg"
if [ "$GIT_COMMITTER_EMAIL" = "$OLD_EMAIL" -o "$GIT_COMMITTER_EMAIL" = "" ]; then
    export GIT_COMMITTER_NAME="$CORRECT_NAME"
    export GIT_COMMITTER_EMAIL="$CORRECT_EMAIL"
fi
if [ "$GIT_AUTHOR_EMAIL" = "$OLD_EMAIL" -o "$GIT_AUTHOR_EMAIL" = "" ]; then
    export GIT_AUTHOR_NAME="$CORRECT_NAME"
    export GIT_AUTHOR_EMAIL="$CORRECT_EMAIL"
fi
' --tag-name-filter cat -- --branches --tags

