#!/bin/sh
# Set file modification date to date of last revision of file as in CVS

for FILE in $(git ls-files); do
    DATE=$(git log --pretty=format:%cd -n 1 --date=iso -- "$FILE")
    touch -m --date "$DATE" "$FILE"
done

