SELECT CASE `name`
        WHEN 'openoffice-langpack-bg'   THEN 'openoffice-langpack'
        WHEN 'tesseract-bul'            THEN 'tesseract-lang'
        WHEN 'tesseract-eng'            THEN 'tesseract-lang'
        WHEN 'tesseract-equ'            THEN 'tesseract-lang'
        WHEN 'tesseract-osd'            THEN 'tesseract-lang'
        ELSE `name`
       END AS `name`,
       serie
  FROM packages
 WHERE `name` IN ('asn1crypto',
                  'bcrypt',
                  'cffi',
                  'chromaprint',
                  'cppcheck',
                  'cppclean',
                  'cryptography',
                  'ctemplate',
                  'elinks',
                  'enum34',
                  'extra-cmake-modules',
                  'flite',
                  'freeipmi',
                  'freeradius-server',
                  'freerdp',
                  'frei0r-plugins',
                  'fribidi',
                  'fswebcam',
                  'gdal',
                  'geos',
                  'gl2ps',
                  'go',
                  'gtest',
                  'gtksourceview',
                  'hdf5',
                  'idna',
                  'ipaddress',
                  'ipcalc',
                  'iucode_tool',
                  'jdk',
                  'json-c',
                  'kvazaar',
                  'libbluray',
                  'libbs2b',
                  'libconfig',
                  'libdbus-c++',
                  'libebur128',
                  'libelf',
                  'libgme',
                  'libgxps',
                  'libilbc',
                  'libiscsi',
                  'libmaxminddb',
                  'libnfs',
                  'libopenmpt',
                  'libquvi',
                  'libquvi-scripts',
                  'libssh2',
                  'libxml++',
                  'ltrace',
                  'lzip',
                  'minidlna',
                  'mkvtoolnix',
                  'mysql-connector-python',
                  'mysql-router',
                  'mysql-shell',
                  'mysql-utilities',
                  'ncdu',
                  'netcdf',
                  'numactl',
                  'numpy',
                  'open-vm-tools',
                  'openal',
                  'openldap',
                  'openoffice-langpack-bg',
                  'opus',
                  'opus-tools',
                  'opusfile',
                  'pcsc-omnikey',
                  'proj',
                  'protobuf',
                  'pyasn1',
                  'pygments',
                  'pynacl',
                  'python-ecdsa',
                  'rapidjson',
                  'recutils',
                  'rubberband',
                  'sbc',
                  'setuptools',
                  'six',
                  'snappy',
                  'soxr',
                  'speexdsp',
                  'tesseract',
                  'tesseract-bul',
                  'tesseract-eng',
                  'tesseract-equ',
                  'tesseract-osd',
                  'tinyxml',
                  'tinyxml2',
                  'v4l-utils',
                  'vamp-plugin-sdk',
                  'vid.stab',
                  'vsqlite++',
                  'x265',
                  'xorgxrdp',
                  'xrdp')
  GROUP BY 1, 2;
